### ISSUE TITLE
Data Grafik di Dashboard tidak benar 

### ISSUE THREAD

**Issue by rosyidpaundra** [rifandani/trishop#28]
**Describe the bug**
Data pada grafik tidak sesuai dengan data yang di inputkan user

**To Reproduce**
masuk pada halaman dashboard, lalu cek grafik

**Expected behavior**
seharusnya data keterangan warna merah adalah 40%

**Screenshots**
![orange](https://github.com/rifandani/trishop/assets/147139310/9f67c8dd-901f-4eec-be5a-1fe5dd4fd53c)

- OS: [ ]
- Browser [ chrome, ]
- Version [22]

**Additional context**
-

**Comment by rifandani** [comment]
Halo @rosyidpaundra . 
Kalau saya liat dari image nya itu spertinya bukan dari project ini deh. 
Btw project ini sudah ngga saya maintain lagi, jadi bisa di fork aj repo nya & nnti kmu bisa nambah fitur / bug fix sendiri.
